### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The included URLconf 'mysite.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.

### ISSUE THREAD

**Issue by sakethreddy91** [mgrouchy/django-stronghold#77]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\anaconda\envs\sales\lib\site-packages\django\urls\resolvers.py", line 581, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\sales\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\anaconda\envs\sales\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda\envs\sales\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "D:\anaconda\envs\sales\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "D:\anaconda\envs\sales\lib\site-packages\django\urls\resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "D:\anaconda\envs\sales\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\anaconda\envs\sales\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name))
django.core.exceptions.ImproperlyConfigured: The included URLconf 'mysite.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.

**Comment by codetexi** [comment]
eg:
urlpatterns = [

    path('view/<int:pk>',product_view,name='view'),
   
]

Note : urlpatterns must be written in same case as i mentioned above it must not be URLpatterns nor urlpattern........
